Updated support for Solaris, and made PAM sleep quietly when told to do so.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -134,11 +134,13 @@ AC_ARG_ENABLE(shadow,
       use_shadow=""
     else
       use_shadow="-DUSESHADOW"
+      force_shadow="yes"
     fi ])
 AC_ARG_ENABLE(autoshadow,
   [  --enable-autoshadow     enabled auto-detection of shadowed passwords],
   [ if test "$enableval" != "no" ; then
       use_shadow="-DUSESHADOW -DAUTOSHADOW"
+      force_shadow="yes"
     fi ])
 AC_CHECK_LIB(security, set_auth_parameters, LIBS="$LIBS -lsecurity")
 AC_CHECK_HEADERS(sys/security.h)
@@ -148,8 +150,14 @@ AC_CHECK_FUNCS(set_auth_parameters getprpwent)
 
 dnl Checks for installation user/group
 
-test x"$install_user" = x && install_user=`id -un`
-test x"$install_group" = x && install_group=`id -gn`
+if test -f /usr/xpg4/bin/id ; then
+  id_prog="/usr/xpg4/bin/id"
+else
+  id_prog=`which id`
+fi
+
+test x"$install_user" = x && install_user=`$id_prog -un`
+test x"$install_group" = x && install_group=`$id_prog -gn`
 
 AC_SUBST(install_user)
 AC_SUBST(install_group)
@@ -164,15 +172,17 @@ AC_CHECK_HEADERS(shadow.h,
       use_shadow="-DUSESHADOW"
     fi ])
 AC_CHECK_HEADERS(security/pam_appl.h,
-  [ if test "$use_shadow" != ""; then
-      use_shadow=""
+  [ if test "$force_shadow" != "yes"; then
+	if "$use_shadow" != ""; then
+	  use_shadow=""
 	fi
 
 	AC_CHECK_LIB(dl,dlopen)
 
 	if test `echo $ac_addl_modules | grep -c mod_pam` = "0"; then
-		ac_addl_modules="mod_pam.o $ac_addl_modules"
-		ac_build_addl_modules="modules/mod_pam.o $ac_build_addl_modules"
+	  ac_addl_modules="mod_pam.o $ac_addl_modules"
+	  ac_build_addl_modules="modules/mod_pam.o $ac_build_addl_modules"
+	fi
     fi ])
 
 AC_CHECK_HEADERS(ctype.h getopt.h crypt.h bstring.h strings.h)
@@ -397,14 +407,14 @@ LIBS="-lsupp $LIBS"
 dnl Module handling.
 for module in $ac_addl_modules; do
   src=`echo "$module" | sed -e 's/\.o$//'`.c;
-  if ! test -f modules/$src; then
-    echo "source file 'modules/$src' cannot be found -- aborting"
-    exit 1
-  else
+  if test -f modules/$src; then
     alib=`cat modules/$src | grep "\\\$Libraries:" | sed -e 's/^.*\$Libraries: \(.*\)\\$/\1/'`
     test x"$alib" = x || ac_addl_libs="$alib $ac_addl_libs"
     adir=`cat modules/$src | grep "\\\$Directories:" | sed -e 's/^.*\$Directories: \(.*\)\\$/\1/'`
     test x"$adir" = x || ac_addl_dirs="$adir $ac_addl_dirs"
+  else
+    echo "source file 'modules/$src' cannot be found -- aborting"
+    exit 1
   fi
 done
 
