Updated configure.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -33005,6 +33005,83 @@ fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
+
+  { echo "$as_me:$LINENO: checking whether linking with OpenSSL has complete ECC support" >&5
+echo $ECHO_N "checking whether linking with OpenSSL has complete ECC support... $ECHO_C" >&6; }
+  saved_libs="$LIBS"
+
+    LIBS=`echo "$LIBS" | sed -e 's/-lsupp//g'`;
+  LIBS="$LIBS -lcrypto"
+
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+      #include <openssl/ec.h>
+      #include <openssl/ecdh.h>
+      #include <openssl/ecdsa.h>
+      #include <openssl/evp.h>
+      #include <openssl/objects.h>
+      #include <openssl/opensslv.h>
+      #if OPENSSL_VERSION_NUMBER < 0x0090807f /* 0.9.8g */
+      # error "OpenSSL < 0.9.8g has unreliable ECC code"
+      #endif
+
+int
+main ()
+{
+
+      EC_KEY *e = EC_KEY_new_by_curve_name(NID_secp521r1);
+      const EVP_MD *m = EVP_sha512();
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+
+      { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define PR_USE_OPENSSL_ECC 1
+_ACEOF
+,
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+      { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+  LIBS="$saved_libs"
 fi
 
 if test x"$pr_use_postgres" = xyes; then
