Updated configure.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -466,7 +466,7 @@ ac_includes_default="\
 ac_subdirs_all="$ac_subdirs_all lib/libltdl"
 ac_subdirs_all="$ac_subdirs_all $ac_shared_module_dirs"
 ac_subdirs_all="$ac_subdirs_all $ac_static_module_dirs"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os OSREL OSTYPE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT SET_MAKE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP CPP CXX CXXFLAGS ac_ct_CXX CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL BINDIR DATADIR INCLUDEDIR LIBEXECDIR LOCALSTATEDIR PREFIX SBINDIR SYSCONFDIR subdirs install_user install_group ALLOCA ENABLE_NLS GLUE_MODULE_OBJS INSTALL_STRIP INCLTDL INSTALL_DEPS LIB_DEPS LIB_OBJS LIBTOOL_DEPS LIBLTDL MAIN_LDFLAGS MAIN_LIBS MODULE_DEPS MODULE_LDFLAGS SHARED_MODULE_DIRS SHARED_MODULE_LIBS SHARED_MODULE_OBJS STATIC_MODULE_DIRS STATIC_MODULE_OBJS BUILD_SHARED_MODULE_OBJS BUILD_STATIC_MODULE_OBJS ADDL_DIRS INCLUDES LIBDIRS LIBRARIES CURSES_LIBS UTILS_LIBS VERSION LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os OSREL OSTYPE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT SET_MAKE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP CPP CXX CXXFLAGS ac_ct_CXX CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL BINDIR DATADIR INCLUDEDIR LIBEXECDIR LOCALSTATEDIR PREFIX SBINDIR SYSCONFDIR subdirs install_user install_group ALLOCA ENABLE_NLS GLUE_MODULE_OBJS INSTALL_STRIP INCLTDL INSTALL_DEPS LIB_DEPS LIB_OBJS LIBTOOL_DEPS LIBLTDL MAIN_LDFLAGS MAIN_LIBS MODULE_DEPS MODULE_LDFLAGS SHARED_MODULE_DIRS SHARED_MODULE_LIBS SHARED_MODULE_OBJS STATIC_MODULE_DIRS STATIC_MODULE_OBJS BUILD_SHARED_MODULE_OBJS BUILD_STATIC_MODULE_ARCHIVES BUILD_STATIC_MODULE_OBJS ADDL_DIRS INCLUDES LIBDIRS LIBRARIES CURSES_LIBS UTILS_LIBS VERSION LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -36544,20 +36544,49 @@ for module in $ac_static_modules ; do
     src=`echo "$module" | sed -e 's/\.o$//'`.c;
     srcinc=`echo "$module" | sed -e 's/\.o$//'`.h;
 
+    srcarch=`cat $srcdir/contrib/$moduledir/$src | grep "\\\$Archive:" | sed -e 's/^.*\$Archive: \(.*\)\\$/\1/'`
     srclib=`cat $srcdir/contrib/$moduledir/$src | grep "\\\$Libraries:" | sed -e 's/^.*\$Libraries: \(.*\)\\$/\1/'`
 
     if test -f $srcdir/contrib/$moduledir/$srcinc ; then
+      if test -z $srcarch ; then
+        incarch=`cat $srcdir/contrib/$moduledir/$srcinc | grep "\\\$Archive:" | sed -e 's/^.*\$Archive: \(.*\)\\$/\1/'`
+      else
+        incarch=
+      fi
+
       inclib=`cat $srcdir/contrib/$moduledir/$srcinc | grep "\\\$Libraries:" | sed -e 's/^.*\$Libraries: \(.*\)\\$/\1/'`
     else
+      incarch=
       inclib=
     fi
 
     srcinc_in="$srcinc.in"
     if test -f $srcdir/contrib/$moduledir/$srcinc_in ; then
+      if test -z $srcarch -a test -z $incarch ; then
+        incarch=`cat $srcdir/contrib/$moduledir/$srcinc_in | grep "\\\$Archive:" | sed -e 's/^.*\$Archive: \(.*\)\\$/\1/'`
+      else
+        incarch=
+      fi
+
       inclib=`cat $srcdir/contrib/$moduledir/$srcinc_in | grep "\\\$Libraries:" | sed -e 's/^.*\$Libraries: \(.*\)\\$/\1/'`
     else
+      incarch=
       inclib=
     fi
+
+            for thearch in $srcarch $incarch; do
+      archive=`echo "$thearch" | sed -e 's/\.a$//'`
+
+      if test x"$archive" != x"$moduledir" ; then
+        { { echo "$as_me:$LINENO: error: specified archive '$thearch' does not match expected module archive name '$moduledir.a' -- aborting" >&5
+echo "$as_me: error: specified archive '$thearch' does not match expected module archive name '$moduledir.a' -- aborting" >&2;}
+   { (exit 1); exit 1; }; }
+      fi
+
+      ac_static_modules=`echo "$ac_static_modules" | sed -e "s/$module//g"`
+      ac_build_static_modules=`echo "$ac_build_static_modules" | sed -e "s/modules\/$module//g"`
+      ac_build_static_module_archives="$ac_build_static_module_archives contrib/$moduledir/$thearch"
+    done
 
         for thelib in $srclib $inclib; do
       dup="no"
@@ -36714,6 +36743,7 @@ fi
 STATIC_MODULE_DIRS="$ac_static_module_dirs"
 STATIC_MODULE_OBJS="$ac_core_modules $ac_static_modules"
 BUILD_SHARED_MODULE_OBJS="$ac_build_shared_modules"
+BUILD_STATIC_MODULE_ARCHIVES="$ac_build_static_module_archives"
 BUILD_STATIC_MODULE_OBJS="$ac_build_core_modules $ac_build_static_modules"
 SHARED_MODULE_LIBS="$ac_orig_libs"
 VERSION=`cat $srcdir/include/version.h | grep "#define VERSION " | sed -e 's/^.*\"\(.*\)\"/\1/'`
@@ -36814,6 +36844,7 @@ my_libs="\"$LIBS\""
 cat >>confdefs.h <<_ACEOF
 #define PR_BUILD_LIBS $my_libs
 _ACEOF
+
 
 
 
@@ -37553,6 +37584,7 @@ s,@SHARED_MODULE_OBJS@,$SHARED_MODULE_OBJS,;t t
 s,@STATIC_MODULE_DIRS@,$STATIC_MODULE_DIRS,;t t
 s,@STATIC_MODULE_OBJS@,$STATIC_MODULE_OBJS,;t t
 s,@BUILD_SHARED_MODULE_OBJS@,$BUILD_SHARED_MODULE_OBJS,;t t
+s,@BUILD_STATIC_MODULE_ARCHIVES@,$BUILD_STATIC_MODULE_ARCHIVES,;t t
 s,@BUILD_STATIC_MODULE_OBJS@,$BUILD_STATIC_MODULE_OBJS,;t t
 s,@ADDL_DIRS@,$ADDL_DIRS,;t t
 s,@INCLUDES@,$INCLUDES,;t t
