Updating the configure script.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -305,7 +305,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os OSREL OSTYPE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT SET_MAKE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA RANLIB ac_ct_RANLIB CPP EGREP install_user install_group ALLOCA MODULES BUILD_MODULES ADDL_DIRS INCLUDES LIBRARIES VERSION LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os OSREL OSTYPE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT SET_MAKE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA RANLIB ac_ct_RANLIB CPP EGREP install_user install_group ALLOCA LIB_OBJS MODULES BUILD_MODULES ADDL_DIRS INCLUDES LIBRARIES VERSION LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -892,11 +892,18 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+
+     --without-getopt        prevent proftpd from using its bundled getopt
+                          implementation.  This is done automatically if
+                          the host supports getopt, but may need to be
+                          explicitly used when combining proftpd with other
+                          applications, such as MySQL
+
   --with-includes=LIST    add additional include paths to proftpd
                           LIST is a ':' separated list of include paths to add
                           e.g. --with-includes=/some/mysql/include:/my/include
 
-  --with-libraries=LIST    add additional library paths to proftpd
+  --with-libraries=LIST   add additional library paths to proftpd
                           LIST is a ':' separated list of include paths to add
                           e.g. --with-libraries=/some/mysql/libdir:/my/libs
 
@@ -2802,6 +2809,27 @@ rm -f conftest.$ac_objext conftest.$ac_ext
 fi
 
 
+
+ac_lib_objs="pr_fnmatch.o strsep.o vsnprintf.o glibc-glob.o glibc-mkstemp.o pr-syslog.o pwgrent.o"
+ac_pr_check_getopt="yes"
+
+
+# Check whether --with-getopt or --without-getopt was given.
+if test "${with_getopt+set}" = set; then
+  withval="$with_getopt"
+
+    if test "$withval" = "no" ; then
+      LIB_OBJS="$ac_lib_objs"
+      ac_pr_check_getopt="no"
+    else
+      LIB_OBJS="$ac_lib_objs getopt.o getopt1.o"
+    fi
+
+else
+
+    LIB_OBJS="$ac_lib_objs getopt.o getopt1.o"
+
+fi;
 
 
 # Check whether --with-includes or --without-includes was given.
@@ -9217,11 +9245,82 @@ _ACEOF
 fi
 done
 
+if test "$ac_pr_check_getopt" = "yes" ; then
+
+for ac_func in getopt
+do
+as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $ac_func" >&5
+echo $ECHO_N "checking for $ac_func... $ECHO_C" >&6
+if eval "test \"\${$as_ac_var+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char $ac_func (); below.  */
+#include <assert.h>
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char $ac_func ();
+char (*f) ();
+
+int
+main ()
+{
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_$ac_func) || defined (__stub___$ac_func)
+choke me
+#else
+f = $ac_func;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_var=yes"
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+eval "$as_ac_var=no"
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_var'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_var'}'`" >&6
+if test `eval echo '${'$as_ac_var'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
+_ACEOF
+
+fi
+done
+
+fi
 
 
 
-
-for ac_func in getopt getopt_long gettimeofday inet_aton
+for ac_func in getopt_long gettimeofday inet_aton
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -11221,6 +11320,7 @@ exec_prefix="$savedExecPrefix"
 
 
 
+
           ac_config_headers="$ac_config_headers config.h"
 
 
@@ -11856,6 +11956,7 @@ s,@EGREP@,$EGREP,;t t
 s,@install_user@,$install_user,;t t
 s,@install_group@,$install_group,;t t
 s,@ALLOCA@,$ALLOCA,;t t
+s,@LIB_OBJS@,$LIB_OBJS,;t t
 s,@MODULES@,$MODULES,;t t
 s,@BUILD_MODULES@,$BUILD_MODULES,;t t
 s,@ADDL_DIRS@,$ADDL_DIRS,;t t
