Updating configure.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -464,7 +464,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all lib/libltdl"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os OSREL OSTYPE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT SET_MAKE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP CPP CXX CXXFLAGS ac_ct_CXX CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL BINDIR INCLUDEDIR LIBEXECDIR LOCALSTATEDIR PREFIX SBINDIR SYSCONFDIR subdirs install_user install_group ALLOCA INSTALL_STRIP INCLTDL INSTALL_DEPS LIB_DEPS LIB_OBJS LIBTOOL_DEPS LIBLTDL MAIN_LDFLAGS MAIN_LIBS MODULE_DEPS MODULE_LDFLAGS MODULE_OBJS BUILD_MODULE_OBJS ADDL_DIRS INCLUDES LIBRARIES CURSES_LIBS VERSION LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os OSREL OSTYPE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT SET_MAKE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP CPP CXX CXXFLAGS ac_ct_CXX CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL BINDIR INCLUDEDIR LIBEXECDIR LOCALSTATEDIR PREFIX SBINDIR SYSCONFDIR subdirs install_user install_group ALLOCA INSTALL_STRIP INCLTDL INSTALL_DEPS LIB_DEPS LIB_OBJS LIBTOOL_DEPS LIBLTDL MAIN_LDFLAGS MAIN_LIBS MODULE_DEPS MODULE_LDFLAGS SHARED_MODULE_OBJS STATIC_MODULE_OBJS BUILD_SHARED_MODULE_OBJS BUILD_STATIC_MODULE_OBJS ADDL_DIRS INCLUDES LIBDIRS LIBRARIES CURSES_LIBS VERSION LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1134,6 +1134,10 @@ Optional Packages:
   --with-modules=LIST     add additional modules to proftpd. LIST is a
                           colon-separated list of modules to add e.g.
                           --with-modules=mod_auth_pam:mod_readme
+
+  --with-shared=LIST      build DSO modules for proftpd. LIST is a
+                          colon-separated list of modules to build as DSOs
+                          e.g. --with-shared=mod_rewrite:mod_ifsession
 
 
 Some influential environment variables:
@@ -3339,7 +3343,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3342 "configure"' > conftest.$ac_ext
+  echo '#line 3346 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -4802,7 +4806,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:4805:" \
+echo "$as_me:4809:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -5856,11 +5860,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:5859: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:5863: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:5863: \$? = $ac_status" >&5
+   echo "$as_me:5867: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6099,11 +6103,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6102: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6106: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6106: \$? = $ac_status" >&5
+   echo "$as_me:6110: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6159,11 +6163,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6162: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6166: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6166: \$? = $ac_status" >&5
+   echo "$as_me:6170: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8344,7 +8348,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8347 "configure"
+#line 8351 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8442,7 +8446,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8445 "configure"
+#line 8449 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10635,11 +10639,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10638: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10642: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10642: \$? = $ac_status" >&5
+   echo "$as_me:10646: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -10695,11 +10699,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10698: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10702: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10702: \$? = $ac_status" >&5
+   echo "$as_me:10706: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12056,7 +12060,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12059 "configure"
+#line 12063 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12154,7 +12158,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12157 "configure"
+#line 12161 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12991,11 +12995,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12994: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12998: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12998: \$? = $ac_status" >&5
+   echo "$as_me:13002: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13051,11 +13055,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13054: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13058: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13058: \$? = $ac_status" >&5
+   echo "$as_me:13062: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15090,11 +15094,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15093: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15097: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15097: \$? = $ac_status" >&5
+   echo "$as_me:15101: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15333,11 +15337,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15336: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15340: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15340: \$? = $ac_status" >&5
+   echo "$as_me:15344: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15393,11 +15397,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15396: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15400: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15400: \$? = $ac_status" >&5
+   echo "$as_me:15404: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17578,7 +17582,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17581 "configure"
+#line 17585 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17676,7 +17680,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17679 "configure"
+#line 17683 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19444,12 +19448,12 @@ fi;
 # Check whether --with-libraries or --without-libraries was given.
 if test "${with_libraries+set}" = set; then
   withval="$with_libraries"
-   ac_addl_libraries=`echo "$withval" | sed -e 's/:/ /g'` ;
-    for ainclude in $ac_addl_libraries; do
-      if test x"$ac_build_addl_libraries" = x ; then
-        ac_build_addl_libraries="-L$ainclude"
+   ac_addl_libdirs=`echo "$withval" | sed -e 's/:/ /g'` ;
+    for alibdir in $ac_addl_libdirs; do
+      if test x"$ac_build_addl_libdirs" = x ; then
+        ac_build_addl_libdirs="-L$alibdir"
       else
-        ac_build_addl_libraries="-L$ainclude $ac_build_addl_libraries"
+        ac_build_addl_libdirs="-L$alibdir $ac_build_addl_libdirs"
       fi
     done
 fi;
@@ -19458,10 +19462,22 @@ fi;
 # Check whether --with-modules or --without-modules was given.
 if test "${with_modules+set}" = set; then
   withval="$with_modules"
-   ac_addl_modules=`echo "$withval" | sed -e 's/:/.o /g'`.o ;
-    for amodule in $ac_addl_modules; do
-      ac_build_addl_modules="modules/$amodule $ac_build_addl_modules"
+   ac_static_modules=`echo "$withval" | sed -e 's/:/.o /g'`.o ;
+    for amodule in $ac_static_modules; do
+      ac_build_static_modules="modules/$amodule $ac_build_static_modules"
     done
+fi;
+
+
+# Check whether --with-shared or --without-shared was given.
+if test "${with_shared+set}" = set; then
+  withval="$with_shared"
+
+    ac_shared_modules=`echo "$withval" | sed -e 's/:/.la /g'`.la ;
+    for amodule in $ac_shared_modules; do
+      ac_build_shared_modules="modules/$amodule $ac_build_shared_modules"
+    done
+
 fi;
 
 
@@ -19516,7 +19532,7 @@ fi;
 if test "${enable_auth_pam+set}" = set; then
   enableval="$enable_auth_pam"
    if test "$enableval" = "no" && \
-       test `echo $ac_addl_modules | grep -c mod_auth_pam` != "0"; then
+       test `echo $ac_static_modules | grep -c mod_auth_pam` != "0"; then
       { { echo "$as_me:$LINENO: error: You cannot run configure with --disable-auth-pam and include mod_auth_pam in --with-modules at the same time" >&5
 echo "$as_me: error: You cannot run configure with --disable-auth-pam and include mod_auth_pam in --with-modules at the same time" >&2;}
    { (exit 1); exit 1; }; }
@@ -23398,9 +23414,9 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
   cat >>confdefs.h <<_ACEOF
 #define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
 _ACEOF
-  if test `echo $ac_addl_modules | grep -c mod_auth_pam` = "0"; then
-        ac_addl_modules="mod_auth_pam.o $ac_addl_modules"
-        ac_build_addl_modules="modules/mod_auth_pam.o $ac_build_addl_modules"
+  if test `echo $ac_static_modules | grep -c mod_auth_pam` = "0"; then
+        ac_static_modules="mod_auth_pam.o $ac_static_modules"
+        ac_build_static_modules="modules/mod_auth_pam.o $ac_build_static_modules"
       fi
 fi
 
@@ -23408,7 +23424,7 @@ done
 
 
 
-  if test `echo $ac_addl_modules | grep -c mod_auth_pam` = "1"; then
+  if test `echo $ac_static_modules | grep -c mod_auth_pam` = "1"; then
 
 	echo "$as_me:$LINENO: checking for pam_start in -lpam" >&5
 echo $ECHO_N "checking for pam_start in -lpam... $ECHO_C" >&6
@@ -23718,8 +23734,8 @@ echo "$as_me:$LINENO: result: $ac_add_mod_cap" >&5
 echo "${ECHO_T}$ac_add_mod_cap" >&6
 
 if test $ac_add_mod_cap = "yes"; then
-  ac_addl_modules="$ac_addl_modules mod_cap.o"
-  ac_build_addl_modules="modules/mod_cap.o $ac_build_addl_modules"
+  ac_static_modules="$ac_static_modules mod_cap.o"
+  ac_build_static_modules="modules/mod_cap.o $ac_build_static_modules"
 fi
 
 
@@ -33113,7 +33129,7 @@ done
 #define HAVE_SOLARIS_SENDFILE 1
 _ACEOF
 
-      ac_build_addl_libraries="-lsendfile $ac_build_addl_libraries"
+      ac_build_addl_libs="-lsendfile $ac_build_addl_libs"
       ;;
   esac
 fi
@@ -34273,49 +34289,78 @@ fi
 
 LIBS="-lsupp $LIBS"
 
-for module in $ac_addl_modules; do
-  addonlibs=""
-  src=`echo "$module" | sed -e 's/\.o$//'`.c;
-  srcinc=`echo "$module" | sed -e 's/\.o$//'`.h;
-  if test -f $srcdir/modules/$src -o -f $srcdir/contrib/$src; then
+for module in $ac_shared_modules; do
+  if test x"$enable_dso" != xyes ; then
+    echo "cannot build shared modules without DSO support -- aborting"
+    exit 1
+  fi
 
+  src=`echo "$module" | sed -e 's/\.la$//'`.c;
+  srcinc=`echo "$module" | sed -e 's/\.la$//'`.h;
+
+  if test -f $srcdir/modules/$src -o -f $srcdir/contrib/$src; then
     if test ! -f $srcdir/modules/$src; then
-	olddir=`pwd`
-	cd $srcdir/modules
-	ln -s ../contrib/$src $src
-	cd $olddir
+      olddir=`pwd`
+      cd $srcdir/modules
+      ln -s ../contrib/$src $src
+      cd $olddir
     fi
 
     if test ! -f $srcdir/include/$srcinc -a -f $srcdir/contrib/$srcinc ; then
-	olddir=`pwd`
-	cd $srcdir/include
-	ln -s ../contrib/$srcinc $srcinc
-	cd $olddir
+      olddir=`pwd`
+      cd $srcdir/include
+      ln -s ../contrib/$srcinc $srcinc
+      cd $olddir
+    fi
+
+
+  else
+    echo "source file '$srcdir/modules/$src' cannot be found -- aborting"
+    exit 1
+  fi
+done
+
+for module in $ac_static_modules; do
+  addonlibs=""
+  src=`echo "$module" | sed -e 's/\.o$//'`.c;
+  srcinc=`echo "$module" | sed -e 's/\.o$//'`.h;
+
+  if test -f $srcdir/modules/$src -o -f $srcdir/contrib/$src; then
+    if test ! -f $srcdir/modules/$src; then
+      olddir=`pwd`
+      cd $srcdir/modules
+      ln -s ../contrib/$src $src
+      cd $olddir
+    fi
+
+    if test ! -f $srcdir/include/$srcinc -a -f $srcdir/contrib/$srcinc ; then
+      olddir=`pwd`
+      cd $srcdir/include
+      ln -s ../contrib/$srcinc $srcinc
+      cd $olddir
     fi
 
     srclib=`cat $srcdir/modules/$src | grep "\\\$Libraries:" | sed -e 's/^.*\$Libraries: \(.*\)\\$/\1/'`
 
     if test -f $srcdir/include/$srcinc ; then
-        inclib=`cat $srcdir/include/$srcinc | grep "\\\$Libraries:" | sed -e 's/^.*\$Libraries: \(.*\)\\$/\1/'`
+      inclib=`cat $srcdir/include/$srcinc | grep "\\\$Libraries:" | sed -e 's/^.*\$Libraries: \(.*\)\\$/\1/'`
     else
-        inclib=
+      inclib=
     fi
 
-
         for thelib in $srclib $inclib; do
-	dup="no"
+      dup="no"
 
-	for somelib in $ac_addl_libs $LIBS; do
+      for somelib in $ac_addl_libs $LIBS; do
+        if test "$thelib" = "$somelib"; then
+          dup="yes"
+          break
+        fi
+      done
 
-		if test "$thelib" = "$somelib"; then
-			dup="yes"
-			break
-		fi
-	done
-
-	if test "$dup" = "no"; then
-		addonlibs="$addonlibs $thelib"
-	fi
+      if test "$dup" = "no"; then
+        addonlibs="$addonlibs $thelib"
+      fi
     done
 
     test x"$addonlibs" = x || ac_addl_libs="$addonlibs $ac_addl_libs"
@@ -34324,10 +34369,8 @@ for module in $ac_addl_modules; do
     test x"$adir" = x || ac_addl_dirs="$adir $ac_addl_dirs"
 
   else
-
     echo "source file '$srcdir/modules/$src' cannot be found -- aborting"
     exit 1
-
   fi
 done
 
@@ -34339,9 +34382,12 @@ ac_addl_dirs=`echo "$ac_addl_dirs" | sed -e 's/^ *//'`
 ADDL_DIRS="$ac_addl_dirs"
 
 INCLUDES="$ac_build_addl_includes"
-LIBRARIES="$ac_build_addl_libraries"
-MODULE_OBJS="$ac_core_modules $ac_addl_modules"
-BUILD_MODULE_OBJS="$ac_build_core_modules $ac_build_addl_modules"
+LIBDIRS="$ac_build_addl_libdirs"
+LIBRARIES="$ac_build_addl_libs"
+SHARED_MODULE_OBJS="$ac_shared_modules"
+STATIC_MODULE_OBJS="$ac_core_modules $ac_static_modules"
+BUILD_SHARED_MODULE_OBJS="$ac_build_shared_modules"
+BUILD_STATIC_MODULE_OBJS="$ac_build_core_modules $ac_build_static_modules"
 VERSION=`cat $srcdir/include/version.h | grep "#define VERSION " | sed -e 's/^.*\"\(.*\)\"/\1/'`
 
 pr_saved_prefix="$prefix"
@@ -34419,6 +34465,9 @@ echo "${ECHO_T}yes" >&6
 echo "${ECHO_T}no" >&6
    fi
    rm -f conftest*
+
+
+
 
 
 
@@ -35138,10 +35187,13 @@ s,@MAIN_LDFLAGS@,$MAIN_LDFLAGS,;t t
 s,@MAIN_LIBS@,$MAIN_LIBS,;t t
 s,@MODULE_DEPS@,$MODULE_DEPS,;t t
 s,@MODULE_LDFLAGS@,$MODULE_LDFLAGS,;t t
-s,@MODULE_OBJS@,$MODULE_OBJS,;t t
-s,@BUILD_MODULE_OBJS@,$BUILD_MODULE_OBJS,;t t
+s,@SHARED_MODULE_OBJS@,$SHARED_MODULE_OBJS,;t t
+s,@STATIC_MODULE_OBJS@,$STATIC_MODULE_OBJS,;t t
+s,@BUILD_SHARED_MODULE_OBJS@,$BUILD_SHARED_MODULE_OBJS,;t t
+s,@BUILD_STATIC_MODULE_OBJS@,$BUILD_STATIC_MODULE_OBJS,;t t
 s,@ADDL_DIRS@,$ADDL_DIRS,;t t
 s,@INCLUDES@,$INCLUDES,;t t
+s,@LIBDIRS@,$LIBDIRS,;t t
 s,@LIBRARIES@,$LIBRARIES,;t t
 s,@CURSES_LIBS@,$CURSES_LIBS,;t t
 s,@VERSION@,$VERSION,;t t
