Updating configure.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3991,6 +3991,70 @@ done
 
 
 
+echo "$as_me:$LINENO: checking for set_auth_parameters in -lsecurity" >&5
+echo $ECHO_N "checking for set_auth_parameters in -lsecurity... $ECHO_C" >&6
+if test "${ac_cv_lib_security_set_auth_parameters+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lsecurity  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char set_auth_parameters ();
+int
+main ()
+{
+set_auth_parameters ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_security_set_auth_parameters=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_security_set_auth_parameters=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_security_set_auth_parameters" >&5
+echo "${ECHO_T}$ac_cv_lib_security_set_auth_parameters" >&6
+if test $ac_cv_lib_security_set_auth_parameters = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBSECURITY 1
+_ACEOF
+
+  LIBS="-lsecurity $LIBS"
+
+fi
+
+
 for ac_func in set_auth_parameters
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
@@ -4071,15 +4135,18 @@ if test `eval echo '${'$as_ac_var'}'` = yes; then
 #define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
 _ACEOF
 
-else
+fi
+done
 
-echo "$as_me:$LINENO: checking for set_auth_parameters in -lsecurity" >&5
-echo $ECHO_N "checking for set_auth_parameters in -lsecurity... $ECHO_C" >&6
-if test "${ac_cv_lib_security_set_auth_parameters+set}" = set; then
+
+
+echo "$as_me:$LINENO: checking for getprpwent in -lsec" >&5
+echo $ECHO_N "checking for getprpwent in -lsec... $ECHO_C" >&6
+if test "${ac_cv_lib_sec_getprpwent+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lsecurity  $LIBS"
+LIBS="-lsec  $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
@@ -4094,11 +4161,11 @@ extern "C"
 #endif
 /* We use char because int might match the return type of a gcc2
    builtin and then its argument prototype would still apply.  */
-char set_auth_parameters ();
+char getprpwent ();
 int
 main ()
 {
-set_auth_parameters ();
+getprpwent ();
   ;
   return 0;
 }
@@ -4115,29 +4182,26 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_lib_security_set_auth_parameters=yes
+  ac_cv_lib_sec_getprpwent=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-ac_cv_lib_security_set_auth_parameters=no
+ac_cv_lib_sec_getprpwent=no
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_security_set_auth_parameters" >&5
-echo "${ECHO_T}$ac_cv_lib_security_set_auth_parameters" >&6
-if test $ac_cv_lib_security_set_auth_parameters = yes; then
+echo "$as_me:$LINENO: result: $ac_cv_lib_sec_getprpwent" >&5
+echo "${ECHO_T}$ac_cv_lib_sec_getprpwent" >&6
+if test $ac_cv_lib_sec_getprpwent = yes; then
   cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBSECURITY 1
+#define HAVE_LIBSEC 1
 _ACEOF
 
-  LIBS="-lsecurity $LIBS"
+  LIBS="-lsec $LIBS"
 
 fi
-
-fi
-done
 
 
 for ac_func in getprpwent
@@ -4219,71 +4283,6 @@ if test `eval echo '${'$as_ac_var'}'` = yes; then
   cat >>confdefs.h <<_ACEOF
 #define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
 _ACEOF
-
-else
-
-echo "$as_me:$LINENO: checking for getprpwent in -lsec" >&5
-echo $ECHO_N "checking for getprpwent in -lsec... $ECHO_C" >&6
-if test "${ac_cv_lib_sec_getprpwent+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lsec  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char getprpwent ();
-int
-main ()
-{
-getprpwent ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_sec_getprpwent=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_cv_lib_sec_getprpwent=no
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_sec_getprpwent" >&5
-echo "${ECHO_T}$ac_cv_lib_sec_getprpwent" >&6
-if test $ac_cv_lib_sec_getprpwent = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBSEC 1
-_ACEOF
-
-  LIBS="-lsec $LIBS"
-
-fi
 
 fi
 done
