Adding support for a --with-shared configure option, for building DSO (aka shared) modules.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -176,12 +176,12 @@ AC_ARG_WITH(libraries,
     [--with-libraries=LIST],
     [add additional library paths to proftpd. LIST is a colon-separated list of include paths to add e.g. --with-libraries=/some/mysql/libdir:/my/libs])
   ],
-  [ ac_addl_libraries=`echo "$withval" | sed -e 's/:/ /g'` ;
-    for ainclude in $ac_addl_libraries; do
-      if test x"$ac_build_addl_libraries" = x ; then
-        ac_build_addl_libraries="-L$ainclude"
+  [ ac_addl_libdirs=`echo "$withval" | sed -e 's/:/ /g'` ;
+    for alibdir in $ac_addl_libdirs; do
+      if test x"$ac_build_addl_libdirs" = x ; then
+        ac_build_addl_libdirs="-L$alibdir"
       else
-        ac_build_addl_libraries="-L$ainclude $ac_build_addl_libraries"
+        ac_build_addl_libdirs="-L$alibdir $ac_build_addl_libdirs"
       fi
     done ])
 
@@ -190,10 +190,22 @@ AC_ARG_WITH(modules,
     [--with-modules=LIST],
     [add additional modules to proftpd. LIST is a colon-separated list of modules to add e.g. --with-modules=mod_auth_pam:mod_readme])
   ],
-  [ ac_addl_modules=`echo "$withval" | sed -e 's/:/.o /g'`.o ;
-    for amodule in $ac_addl_modules; do
-      ac_build_addl_modules="modules/$amodule $ac_build_addl_modules"
+  [ ac_static_modules=`echo "$withval" | sed -e 's/:/.o /g'`.o ;
+    for amodule in $ac_static_modules; do
+      ac_build_static_modules="modules/$amodule $ac_build_static_modules"
     done ])
+
+AC_ARG_WITH(shared,
+  [AC_HELP_STRING(
+    [--with-shared=LIST],
+    [build DSO modules for proftpd. LIST is a colon-separated list of modules to build as DSOs e.g. --with-shared=mod_rewrite:mod_ifsession])
+  ],
+  [
+    ac_shared_modules=`echo "$withval" | sed -e 's/:/.la /g'`.la ;
+    for amodule in $ac_shared_modules; do
+      ac_build_shared_modules="modules/$amodule $ac_build_shared_modules"
+    done
+  ])
 
 dnl --enable/--disable options.
 
@@ -249,7 +261,7 @@ AC_ARG_ENABLE(auth-pam,
     [enable PAM support (default=yes)])
   ],
   [ if test "$enableval" = "no" && \
-       test `echo $ac_addl_modules | grep -c mod_auth_pam` != "0"; then
+       test `echo $ac_static_modules | grep -c mod_auth_pam` != "0"; then
       AC_MSG_ERROR([You cannot run configure with --disable-auth-pam and include mod_auth_pam in --with-modules at the same time])
     fi ])
 
@@ -740,9 +752,9 @@ dnl The pam test used to disable use_shadow, and I'm not sure why, libpam
 dnl really shouldn't have anything to do with force_shadow or use_shadow.
 if test x"$enable_auth_pam" != xno ; then
   AC_CHECK_HEADERS(security/pam_appl.h pam/pam_appl.h,
-    [ if test `echo $ac_addl_modules | grep -c mod_auth_pam` = "0"; then
-        ac_addl_modules="mod_auth_pam.o $ac_addl_modules"
-        ac_build_addl_modules="modules/mod_auth_pam.o $ac_build_addl_modules"
+    [ if test `echo $ac_static_modules | grep -c mod_auth_pam` = "0"; then
+        ac_static_modules="mod_auth_pam.o $ac_static_modules"
+        ac_build_static_modules="modules/mod_auth_pam.o $ac_build_static_modules"
       fi ])
 
   dnl This next check looks funky due to a linker problem with some versions
@@ -755,7 +767,7 @@ if test x"$enable_auth_pam" != xno ; then
   dnl and is picked up at configure time.  The only thing we need is to add
   dnl -ldl in the event of broken PAM.
 
-  if test `echo $ac_addl_modules | grep -c mod_auth_pam` = "1"; then
+  if test `echo $ac_static_modules | grep -c mod_auth_pam` = "1"; then
 
 	AC_CHECK_LIB(pam, pam_start,
 		[AC_DEFINE(HAVE_PAM)],
@@ -787,8 +799,8 @@ AC_MSG_CHECKING([whether to enable mod_cap])
 AC_MSG_RESULT($ac_add_mod_cap)
 
 if test $ac_add_mod_cap = "yes"; then
-  ac_addl_modules="$ac_addl_modules mod_cap.o"
-  ac_build_addl_modules="modules/mod_cap.o $ac_build_addl_modules"
+  ac_static_modules="$ac_static_modules mod_cap.o"
+  ac_build_static_modules="modules/mod_cap.o $ac_build_static_modules"
 fi
 
 AC_CHECK_HEADERS(ctype.h getopt.h crypt.h bstring.h inttypes.h limits.h)
@@ -1190,7 +1202,7 @@ if test x"$enable_sendfile" = xyes ; then
     "Solaris")
       AC_CHECK_HEADERS(sys/sendfile.h)
       AC_DEFINE(HAVE_SOLARIS_SENDFILE)
-      ac_build_addl_libraries="-lsendfile $ac_build_addl_libraries"
+      ac_build_addl_libs="-lsendfile $ac_build_addl_libs"
       ;;
   esac
 fi
@@ -1399,50 +1411,80 @@ dnl Add the proftpd support library
 LIBS="-lsupp $LIBS"
 
 dnl Module handling.
-for module in $ac_addl_modules; do
-  addonlibs=""
-  src=`echo "$module" | sed -e 's/\.o$//'`.c;
-  srcinc=`echo "$module" | sed -e 's/\.o$//'`.h;
-  if test -f $srcdir/modules/$src -o -f $srcdir/contrib/$src; then
+for module in $ac_shared_modules; do
+  if test x"$enable_dso" != xyes ; then
+    echo "cannot build shared modules without DSO support -- aborting"
+    exit 1
+  fi
 
+  src=`echo "$module" | sed -e 's/\.la$//'`.c;
+  srcinc=`echo "$module" | sed -e 's/\.la$//'`.h;
+
+  if test -f $srcdir/modules/$src -o -f $srcdir/contrib/$src; then
     if test ! -f $srcdir/modules/$src; then
-	olddir=`pwd`
-	cd $srcdir/modules
-	ln -s ../contrib/$src $src
-	cd $olddir
+      olddir=`pwd`
+      cd $srcdir/modules
+      ln -s ../contrib/$src $src
+      cd $olddir
     fi
 
     if test ! -f $srcdir/include/$srcinc -a -f $srcdir/contrib/$srcinc ; then
-	olddir=`pwd`
-	cd $srcdir/include
-	ln -s ../contrib/$srcinc $srcinc
-	cd $olddir
+      olddir=`pwd`
+      cd $srcdir/include
+      ln -s ../contrib/$srcinc $srcinc
+      cd $olddir
+    fi
+
+    dnl Need to handle the $Libraries$ tag in shared modules
+
+  else
+    echo "source file '$srcdir/modules/$src' cannot be found -- aborting"
+    exit 1
+  fi
+done
+
+for module in $ac_static_modules; do
+  addonlibs=""
+  src=`echo "$module" | sed -e 's/\.o$//'`.c;
+  srcinc=`echo "$module" | sed -e 's/\.o$//'`.h;
+
+  if test -f $srcdir/modules/$src -o -f $srcdir/contrib/$src; then
+    if test ! -f $srcdir/modules/$src; then
+      olddir=`pwd`
+      cd $srcdir/modules
+      ln -s ../contrib/$src $src
+      cd $olddir
+    fi
+
+    if test ! -f $srcdir/include/$srcinc -a -f $srcdir/contrib/$srcinc ; then
+      olddir=`pwd`
+      cd $srcdir/include
+      ln -s ../contrib/$srcinc $srcinc
+      cd $olddir
     fi
 
     srclib=`cat $srcdir/modules/$src | grep "\\\$Libraries:" | sed -e 's/^.*\$Libraries: \(.*\)\\$/\1/'`
 
     if test -f $srcdir/include/$srcinc ; then
-        inclib=`cat $srcdir/include/$srcinc | grep "\\\$Libraries:" | sed -e 's/^.*\$Libraries: \(.*\)\\$/\1/'`
+      inclib=`cat $srcdir/include/$srcinc | grep "\\\$Libraries:" | sed -e 's/^.*\$Libraries: \(.*\)\\$/\1/'`
     else
-        inclib= 
+      inclib= 
     fi
-
 
     dnl Test for duplicate libraries, just in case.
     for thelib in $srclib $inclib; do
-	dup="no"
+      dup="no"
 
-	for somelib in $ac_addl_libs $LIBS; do
-
-		if test "$thelib" = "$somelib"; then
-			dup="yes"
-			break
-		fi
-	done
+      for somelib in $ac_addl_libs $LIBS; do
+        if test "$thelib" = "$somelib"; then
+          dup="yes"
+          break
+        fi
+      done
 	
-	if test "$dup" = "no"; then
-		addonlibs="$addonlibs $thelib"
-	fi
+      if test "$dup" = "no"; then
+        addonlibs="$addonlibs $thelib"
+      fi
     done
 
     test x"$addonlibs" = x || ac_addl_libs="$addonlibs $ac_addl_libs"
@@ -1451,10 +1493,8 @@ for module in $ac_addl_modules; do
     test x"$adir" = x || ac_addl_dirs="$adir $ac_addl_dirs"
 
   else
-
     echo "source file '$srcdir/modules/$src' cannot be found -- aborting"
     exit 1
-
   fi
 done
 
@@ -1466,9 +1506,12 @@ ac_addl_dirs=`echo "$ac_addl_dirs" | sed -e 's/^ *//'`
 ADDL_DIRS="$ac_addl_dirs"
 
 INCLUDES="$ac_build_addl_includes"
-LIBRARIES="$ac_build_addl_libraries"
-MODULE_OBJS="$ac_core_modules $ac_addl_modules"
-BUILD_MODULE_OBJS="$ac_build_core_modules $ac_build_addl_modules"
+LIBDIRS="$ac_build_addl_libdirs"
+LIBRARIES="$ac_build_addl_libs"
+SHARED_MODULE_OBJS="$ac_shared_modules"
+STATIC_MODULE_OBJS="$ac_core_modules $ac_static_modules"
+BUILD_SHARED_MODULE_OBJS="$ac_build_shared_modules"
+BUILD_STATIC_MODULE_OBJS="$ac_build_core_modules $ac_build_static_modules"
 VERSION=`cat $srcdir/include/version.h | grep "#define VERSION " | sed -e 's/^.*\"\(.*\)\"/\1/'`
 
 dnl Substitute in our configuration paths as appropriate.  We also have to
@@ -1531,10 +1574,13 @@ AC_SUBST(MAIN_LDFLAGS)
 AC_SUBST(MAIN_LIBS)
 AC_SUBST(MODULE_DEPS)
 AC_SUBST(MODULE_LDFLAGS)
-AC_SUBST(MODULE_OBJS)
-AC_SUBST(BUILD_MODULE_OBJS)
+AC_SUBST(SHARED_MODULE_OBJS)
+AC_SUBST(STATIC_MODULE_OBJS)
+AC_SUBST(BUILD_SHARED_MODULE_OBJS)
+AC_SUBST(BUILD_STATIC_MODULE_OBJS)
 AC_SUBST(ADDL_DIRS)
 AC_SUBST(INCLUDES)
+AC_SUBST(LIBDIRS)
 AC_SUBST(LIBRARIES)
 AC_SUBST(CURSES_LIBS)
 AC_SUBST(VERSION)
