Working on ASAN support.  At least make it more conditional, i.e. you now need to explicitly use --enable-devel=sanitize.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20794,19 +20794,6 @@ echo "${ECHO_T}no" >&6; }
    fi
    rm -f conftest*
 
-      { echo "$as_me:$LINENO: checking whether ${CC-cc} accepts -fsanitize=address" >&5
-echo $ECHO_N "checking whether ${CC-cc} accepts -fsanitize=address... $ECHO_C" >&6; }
-   echo 'void f(){}' > conftest.c
-   if test -z "`${CC-cc} -c -fsanitize=address conftest.c 2>&1`"; then
-     { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-     CFLAGS="$CFLAGS -fsanitize=address"
-   else
-     { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-   fi
-   rm -f conftest*
-
 
 
       if test `echo $enableval | grep -c coredump` = "1" ; then
@@ -20829,6 +20816,84 @@ echo "${ECHO_T}no" >&6; }
       if test `echo $enableval | grep -c profile` = "1" ; then
         pr_devel_cflags="-DPR_DEVEL_PROFILE -p -pg $pr_devel_cflags"
         pr_devel_libs="-pg $pr_devel_libs"
+      fi
+
+      if test `echo $enableval | grep -c sanitize` = "1" ; then
+        { echo "$as_me:$LINENO: checking whether ${CC-cc} accepts -fsanitize=address" >&5
+echo $ECHO_N "checking whether ${CC-cc} accepts -fsanitize=address... $ECHO_C" >&6; }
+   echo 'void f(){}' > conftest.c
+   if test -z "`${CC-cc} -c -fsanitize=address conftest.c 2>&1`"; then
+     { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+     CFLAGS="$CFLAGS -fsanitize=address"
+   else
+     { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+   fi
+   rm -f conftest*
+
+
+        # Determine whether we need to link with libasan (gcc) or not (clang)
+        { echo "$as_me:$LINENO: checking whether the C compiler accepts -lasan" >&5
+echo $ECHO_N "checking whether the C compiler accepts -lasan... $ECHO_C" >&6; }
+        saved_ldflags=$LDFLAGS
+        LDFLAGS="-lasan $LDFLAGS"
+        cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+
+            int i;
+            i = 7;
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+
+            { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+            pr_devel_libs="-lasan $pr_devel_libs"
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+            { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+        LDFLAGS=$saved_ldflags
       fi
 
 
