Updated configure.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1613,7 +1613,7 @@ Optional Packages:
                           --with-includes=/some/mysql/include:/my/include
 
   --with-libraries=LIST   add additional library paths to proftpd. LIST is a
-                          colon-separated list of include paths to add e.g.
+                          colon-separated list of library paths to add e.g.
                           --with-libraries=/some/mysql/libdir:/my/libs
 
   --with-modules=LIST     add additional modules to proftpd. LIST is a
@@ -12838,15 +12838,23 @@ fi
 if test "${with_includes+set}" = set; then
   withval=$with_includes;
     if test x"$withval" != x; then
-      ac_addl_includes=`echo "$withval" | sed -e 's/:/ /g'` ;
-      for ainclude in $ac_addl_includes; do
-        if test x"$ac_build_addl_includes" = x ; then
-          ac_build_addl_includes="-I$ainclude"
-        else
-          ac_build_addl_includes="-I$ainclude $ac_build_addl_includes"
-        fi
-      done
-      CPPFLAGS="$CPPFLAGS $ac_build_addl_includes"
+      if test x"$withval" = xyes; then
+        { { echo "$as_me:$LINENO: error: --with-includes parameter missing required colon-separated list of include paths" >&5
+echo "$as_me: error: --with-includes parameter missing required colon-separated list of include paths" >&2;}
+   { (exit 1); exit 1; }; }
+      fi
+
+      if test x"$withval" != xno; then
+        ac_addl_includes=`echo "$withval" | sed -e 's/:/ /g'` ;
+        for ainclude in $ac_addl_includes; do
+          if test x"$ac_build_addl_includes" = x ; then
+            ac_build_addl_includes="-I$ainclude"
+          else
+            ac_build_addl_includes="-I$ainclude $ac_build_addl_includes"
+          fi
+        done
+        CPPFLAGS="$CPPFLAGS $ac_build_addl_includes"
+      fi
     fi
 
 fi
@@ -12857,15 +12865,23 @@ fi
 if test "${with_libraries+set}" = set; then
   withval=$with_libraries;
     if test x"$withval" != x; then
-      ac_addl_libdirs=`echo "$withval" | sed -e 's/:/ /g'` ;
-      for alibdir in $ac_addl_libdirs; do
-        if test x"$ac_build_addl_libdirs" = x ; then
-          ac_build_addl_libdirs="-L$alibdir"
-        else
-          ac_build_addl_libdirs="-L$alibdir $ac_build_addl_libdirs"
-        fi
-      done
-      LDFLAGS="$LDFLAGS $ac_build_addl_libdirs"
+      if test x"$withval" = xyes; then
+        { { echo "$as_me:$LINENO: error: --with-libraries parameter missing required colon-separated list of library paths" >&5
+echo "$as_me: error: --with-libraries parameter missing required colon-separated list of library paths" >&2;}
+   { (exit 1); exit 1; }; }
+      fi
+
+      if test x"$withval" != xno; then
+        ac_addl_libdirs=`echo "$withval" | sed -e 's/:/ /g'` ;
+        for alibdir in $ac_addl_libdirs; do
+          if test x"$ac_build_addl_libdirs" = x ; then
+            ac_build_addl_libdirs="-L$alibdir"
+          else
+            ac_build_addl_libdirs="-L$alibdir $ac_build_addl_libdirs"
+          fi
+        done
+        LDFLAGS="$LDFLAGS $ac_build_addl_libdirs"
+      fi
     fi
 
 fi
@@ -12877,44 +12893,52 @@ ifsession_requested="false"
 if test "${with_modules+set}" = set; then
   withval=$with_modules;
     if test x"$withval" != x; then
-      modules_list=`echo "$withval" | sed -e 's/:/ /g'`;
+      if test x"$withval" = xyes; then
+        { { echo "$as_me:$LINENO: error: --with-modules parameter missing required colon-separated list of modules" >&5
+echo "$as_me: error: --with-modules parameter missing required colon-separated list of modules" >&2;}
+   { (exit 1); exit 1; }; }
+      fi
 
-      for amodule in $modules_list; do
-        if test x"$amodule" == xmod_dso ; then
-          { { echo "$as_me:$LINENO: error: use --enable-dso instead of --with-modules=mod_dso for DSO support" >&5
+      if test x"$withval" != xno; then
+        modules_list=`echo "$withval" | sed -e 's/:/ /g'`;
+
+        for amodule in $modules_list; do
+          if test x"$amodule" == xmod_dso ; then
+            { { echo "$as_me:$LINENO: error: use --enable-dso instead of --with-modules=mod_dso for DSO support" >&5
 echo "$as_me: error: use --enable-dso instead of --with-modules=mod_dso for DSO support" >&2;}
    { (exit 1); exit 1; }; }
-        fi
+          fi
 
-        if test x"$amodule" == xmod_ifsession ; then
+          if test x"$amodule" == xmod_ifsession ; then
             ifsession_requested="true"
-        fi
+          fi
 
-        if test x"$amodule" == xmod_lang ; then
-          { { echo "$as_me:$LINENO: error: use --enable-nls instead of --with-modules=mod_lang for NLS/UTF8 support" >&5
+          if test x"$amodule" == xmod_lang ; then
+            { { echo "$as_me:$LINENO: error: use --enable-nls instead of --with-modules=mod_lang for NLS/UTF8 support" >&5
 echo "$as_me: error: use --enable-nls instead of --with-modules=mod_lang for NLS/UTF8 support" >&2;}
    { (exit 1); exit 1; }; }
-        fi
+          fi
 
-        if test x"$amodule" == xmod_memcache ; then
-          { { echo "$as_me:$LINENO: error: use --enable-memcache instead of --with-modules=mod_memcache for Memcache support" >&5
+          if test x"$amodule" == xmod_memcache ; then
+            { { echo "$as_me:$LINENO: error: use --enable-memcache instead of --with-modules=mod_memcache for Memcache support" >&5
 echo "$as_me: error: use --enable-memcache instead of --with-modules=mod_memcache for Memcache support" >&2;}
    { (exit 1); exit 1; }; }
+          fi
+        done
+
+        ac_static_modules=`echo "$withval" | sed -e 's/:/.o /g'`.o ;
+
+        for amodule in $ac_static_modules; do
+          ac_build_static_modules="modules/$amodule $ac_build_static_modules"
+        done
+
+                        if test x"$ifsession_requested" == xtrue; then
+          ac_static_modules=`echo "$ac_static_modules" | sed -e 's/mod_ifsession\.o//g'`
+          ac_static_modules="$ac_static_modules mod_ifsession.o"
+
+          ac_build_static_modules=`echo "$ac_build_static_modules" | sed -e 's/modules\/mod_ifsession\.o//g'`
+          ac_build_static_modules="$ac_build_static_modules modules/mod_ifsession.o";
         fi
-      done
-
-      ac_static_modules=`echo "$withval" | sed -e 's/:/.o /g'`.o ;
-
-      for amodule in $ac_static_modules; do
-        ac_build_static_modules="modules/$amodule $ac_build_static_modules"
-      done
-
-                  if test x"$ifsession_requested" == xtrue; then
-        ac_static_modules=`echo "$ac_static_modules" | sed -e 's/mod_ifsession\.o//g'`
-        ac_static_modules="$ac_static_modules mod_ifsession.o"
-
-        ac_build_static_modules=`echo "$ac_build_static_modules" | sed -e 's/modules\/mod_ifsession\.o//g'`
-        ac_build_static_modules="$ac_build_static_modules modules/mod_ifsession.o";
       fi
     fi
 
@@ -12936,24 +12960,32 @@ ac_unshareable_modules="mod_auth mod_auth_unix mod_core mod_dso mod_ls mod_xfer 
 if test "${with_shared+set}" = set; then
   withval=$with_shared;
     if test x"$withval" != x; then
-      shared_modules=`echo "$withval" | sed -e 's/:/ /g'`;
+      if test x"$withval" = xyes; then
+        { { echo "$as_me:$LINENO: error: --with-shared parameter missing required colon-separated list of modules" >&5
+echo "$as_me: error: --with-shared parameter missing required colon-separated list of modules" >&2;}
+   { (exit 1); exit 1; }; }
+      fi
 
-      # First double-check that the given list does not contain any
-      # unshareable modules
-      for amodule in $shared_modules; do
-        for smodule in $ac_unshareable_modules; do
-          if test x"$amodule" = x"$smodule"; then
-            { { echo "$as_me:$LINENO: error: cannot build $amodule as a shared module" >&5
+      if test x"$withval" != xno; then
+        shared_modules=`echo "$withval" | sed -e 's/:/ /g'`;
+
+        # First double-check that the given list does not contain any
+        # unshareable modules
+        for amodule in $shared_modules; do
+          for smodule in $ac_unshareable_modules; do
+            if test x"$amodule" = x"$smodule"; then
+              { { echo "$as_me:$LINENO: error: cannot build $amodule as a shared module" >&5
 echo "$as_me: error: cannot build $amodule as a shared module" >&2;}
    { (exit 1); exit 1; }; }
-          fi
+            fi
+          done
         done
-      done
 
-      ac_shared_modules=`echo "$withval" | sed -e 's/:/.la /g'`.la ;
-      for amodule in $ac_shared_modules; do
-        ac_build_shared_modules="modules/$amodule $ac_build_shared_modules"
-      done
+        ac_shared_modules=`echo "$withval" | sed -e 's/:/.la /g'`.la ;
+        for amodule in $ac_shared_modules; do
+          ac_build_shared_modules="modules/$amodule $ac_build_shared_modules"
+        done
+      fi
     fi
 
 fi
@@ -13037,7 +13069,15 @@ pkgconfigdir=NONE
 if test "${with_pkgconfig+set}" = set; then
   withval=$with_pkgconfig;
     if test x"$withval" != x; then
-      pkgconfigdir=`echo "$withval"`
+      if test x"$withval" = xyes; then
+        { { echo "$as_me:$LINENO: error: --with-pkgconfig parameter missing required directory path" >&5
+echo "$as_me: error: --with-pkgconfig parameter missing required directory path" >&2;}
+   { (exit 1); exit 1; }; }
+      fi
+
+      if test x"$withval" != xno; then
+        pkgconfigdir=`echo "$withval"`
+      fi
     fi
 
 fi
@@ -14057,7 +14097,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 14060 "configure"
+#line 14100 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
