Bug#3125 - Support for Mac OS X implementation of POSIX ACLs.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -35890,6 +35890,59 @@ int
 main ()
 {
  acl_entry_t ae;
+        acl_perm_t p = ACL_READ_DATA;
+        (void)acl_get_qualifier(ae);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  pr_cv_func_facl="MacOSX"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+  fi
+
+    if test "$pr_cv_func_facl" = "none"; then
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+ #include <sys/types.h>
+        #ifdef HAVE_SYS_ACL_H
+        # include <sys/acl.h>
+        #endif
+
+int
+main ()
+{
+ acl_entry_t ae;
         (void)acl_get_qualifier(ae);
 
   ;
@@ -36135,6 +36188,14 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 fi
+
+      ;;
+
+    "MacOSX")
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_MACOSX_POSIX_ACL 1
+_ACEOF
 
       ;;
 
@@ -36443,7 +36504,7 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  pr_cv_func_sendfile="Mac OSX"
+  pr_cv_func_sendfile="MacOSX"
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
@@ -36786,7 +36847,7 @@ _ACEOF
       ac_build_addl_libs="-lsendfile $ac_build_addl_libs"
       ;;
 
-    "Mac OSX")
+    "MacOSX")
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_MACOSX_SENDFILE 1
