Updated configure.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -35154,6 +35154,59 @@ rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       LDFLAGS=$old_ldflags
     fi
 
+        if test "$pr_cv_func_sendfile" = "none"; then
+      cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+ #include <sys/types.h>
+          #include <sys/socket.h>
+          #include <sys/uio.h>
+
+int
+main ()
+{
+ int i;
+          off_t o, n;
+          struct sf_hdtr h;
+          (void)sendfile(i,i,o,&n,&h,i);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  pr_cv_func_sendfile="Mac OSX"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+    fi
+
 fi
 { echo "$as_me:$LINENO: result: $pr_cv_func_sendfile" >&5
 echo "${ECHO_T}$pr_cv_func_sendfile" >&6; }
@@ -35478,6 +35531,13 @@ done
 _ACEOF
 
       ac_build_addl_libs="-lsendfile $ac_build_addl_libs"
+      ;;
+
+    "Mac OSX")
+      cat >>confdefs.h <<\_ACEOF
+#define HAVE_MACOSX_SENDFILE 1
+_ACEOF
+
       ;;
   esac
 fi
