Bug#4102 - Failure to build mod_tls when using static libcrypto due to libdl linker errors.
In the course of fixing this issue, I also fixed problems with configure's
detection of EC support in OpenSSL, and make it possible for mod_sftp to
build without zlib support.

diff --git a/contrib/mod_sftp/configure b/contrib/mod_sftp/configure
--- a/contrib/mod_sftp/configure
+++ b/contrib/mod_sftp/configure
@@ -674,6 +674,7 @@ GREP
 EGREP
 INCLUDES
 LIBDIRS
+MODULE_LIBS
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -3858,7 +3859,8 @@ fi
 
 
 
-for ac_header in stdlib.h unistd.h limits.h fcntl.h
+
+for ac_header in stdlib.h unistd.h limits.h fcntl.h zlib.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
@@ -3997,6 +3999,77 @@ fi
 
 done
 
+{ echo "$as_me:$LINENO: checking for inflateInit in -lz" >&5
+echo $ECHO_N "checking for inflateInit in -lz... $ECHO_C" >&6; }
+if test "${ac_cv_lib_z_inflateInit+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lz  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char inflateInit ();
+int
+main ()
+{
+return inflateInit ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_z_inflateInit=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_z_inflateInit=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_z_inflateInit" >&5
+echo "${ECHO_T}$ac_cv_lib_z_inflateInit" >&6; }
+if test $ac_cv_lib_z_inflateInit = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBZ 1
+_ACEOF
+
+   MODULE_LIBS=-lz
+
+fi
+
 
 
 # Check whether --with-includes was given.
@@ -4031,15 +4104,13 @@ fi
 
 
 
-saved_libs="$LIBS"
-LIBS="$LIBS -lcrypto"
 
 { echo "$as_me:$LINENO: checking whether linking with OpenSSL functions requires -ldl" >&5
 echo $ECHO_N "checking whether linking with OpenSSL functions requires -ldl... $ECHO_C" >&6; }
 saved_libs="$LIBS"
 
 LIBS=`echo "$LIBS" | sed -e 's/-lsupp//g'`;
-LIBS="$LIBS -ldl -lcrypto"
+LIBS="-lcrypto -ldl $LIBS"
 
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -4081,7 +4152,7 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 
     { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
-    LIBS="-ldl $saved_libs"
+    LIBS="$saved_libs -ldl"
 
 else
   echo "$as_me: failed program was:" >&5
@@ -4103,7 +4174,7 @@ echo $ECHO_N "checking whether linking with OpenSSL functions requires -lz... $E
 saved_libs="$LIBS"
 
 LIBS=`echo "$LIBS" | sed -e 's/-lsupp//g'`;
-LIBS="$LIBS -lcrypto -lz"
+LIBS="-lcrypto -lz $LIBS"
 
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -4362,6 +4433,7 @@ LIBS="$saved_libs"
 
 INCLUDES="$ac_build_addl_includes"
 LIBDIRS="$ac_build_addl_libdirs"
+
 
 
 
@@ -5047,11 +5119,12 @@ GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
 INCLUDES!$INCLUDES$ac_delim
 LIBDIRS!$LIBDIRS$ac_delim
+MODULE_LIBS!$MODULE_LIBS$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 63; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 64; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
